Add BuildConfig object
fedora-modularity/libmodulemd pull request #489
Opened 2020-10-23 00:31 UTC by sgallagher

Create the basic object type and getters/setters.

Create the YAML parser.

Create unit tests for BuildConfig.

Signed-off-by: Stephen Gallagher <sgallagh@redhat.com>

2020-10-23 00:34 UTC, sgallagher commented
I think the `ModulemdBuildConfig` object is ready to be reviewed now. I implemented the object, the setters/getters and the YAML parser (as well as unit tests for all of those).

It does not include a YAML emitter at this time, because I decided that was "nice-to-have" for debugging, but not important enough to spend time on while under time-pressure.

The `ModulemdPackagerV3` object should be in an equivalent state tomorrow.

2020-10-23 19:41 UTC, mmathesius requested changes

2020-10-23 19:41 UTC, mmathesius commented on modulemd/tests/test-modulemd-build-config.c
> +  /* Read a good YAML file with an unknown key */
```suggestion
  /* Read a YAML file that is missing context */
```

2020-10-23 19:41 UTC, mmathesius commented on modulemd/tests/test-modulemd-build-config.c
> +  /* Read a good YAML file with an unknown key */
```suggestion
  /* Read a YAML file with an empty context */
```

2020-10-23 19:41 UTC, mmathesius commented on modulemd/tests/test-modulemd-build-config.c
> +  /* Read a good YAML file with an unknown key */
```suggestion
  /* Read a YAML file that has a context that is too long */
```

2020-10-23 19:41 UTC, mmathesius commented on modulemd/tests/test-modulemd-build-config.c
> +  /* Read a good YAML file with an unknown key */
```suggestion
  /* Read a YAML file that has a context with a disallowed character */
```

2020-10-23 19:41 UTC, mmathesius commented on modulemd/tests/test-modulemd-build-config.c
> +  /* Read a good YAML file with an unknown key */
```suggestion
  /* Read a YAML file that is missing platform */
```

2020-10-23 20:03 UTC, sgallagher commented on modulemd/include/private/modulemd-build-config.h
> + * MMD_MAXCONTEXTLEN:
Yeah, probably it should be.

2020-10-26 15:47 UTC, sgallagher commented on modulemd/include/private/modulemd-build-config.h
> + * SECTION: modulemd-build-config
I intentionally didn't name it `-private` which is a thing we only do for objects that have both a public and a private header.

2020-10-26 15:48 UTC, sgallagher commented on modulemd/modulemd-build-config.c
> +  if (i >= MMD_MAXCONTEXTLEN)
"There are only two hard problems in computer science..."

2020-10-26 15:54 UTC, sgallagher commented
I fixed up the comments except for renaming the header to `-private`.

2020-10-26 17:22 UTC, merged