Enable Modulemd.read_packager_file/string() to specify module and stream name overrides
fedora-modularity/libmodulemd pull request #536
Opened 2020-12-21 21:30 UTC by mmathesius

This is the C implementation to address RFE #535 that adds new `modulemd_read_packager_file_ext()` and `modulemd_read_packager_string_ext()` API calls.

However, the Python implementation is still missing. I am sure it is possible to integrate this with the Python API so the current `Modulemd.read_packager_file()` and `Modulemd.read_packager_string()` methods automatically do the correct thing if extra module and stream name parameters are provided, but I have no idea how to get GObject to do that.

2020-12-22 18:02 UTC, mmathesius commented
I figured out the Python GObject implementation to automatically use the enhanced versions for `Modulemd.read_packager_file()` and `Modulemd.read_packager_string()`.

A remaining question, however... Should the enhanced versions of the functions also include a `strict` parameter like `Modulemd.ModuleStream.read_file()` and `Modulemd.ModuleStream.read_string()` have?

2021-01-04 13:59 UTC, sgallagher requested changes
You are overthinking the solution here. You should be able to just drop the GObject annotation for `modulemd_read_packager_file()` and add `(rename-to modulemd_read_packager_file)` to the `modulemd_read_packager_file_ext()` implementation.

This will avoid the need to provide a custom override (which we want to minimize whenever possible, since that has to be done per-language-binding, whereas fixing it in the annotations fixes it for all languages.)

2021-01-04 14:02 UTC, sgallagher commented
> A remaining question, however... Should the enhanced versions of the functions also include a `strict` parameter like `Modulemd.ModuleStream.read_file()` and `Modulemd.ModuleStream.read_string()` have?

`read_packager_file()` should *always* be strict. We may need to provide a different way to interact with documents as requested in #535, however. I need to understand better what they're using that information for. We should define the API around their use-case.

2021-01-04 19:23 UTC, mmathesius commented
> You are overthinking the solution here. You should be able to just drop the GObject annotation for `modulemd_read_packager_file()` and add `(rename-to modulemd_read_packager_file)` to the `modulemd_read_packager_file_ext()` implementation.
> 
> This will avoid the need to provide a custom override (which we want to minimize whenever possible, since that has to be done per-language-binding, whereas fixing it in the annotations fixes it for all languages.)

It doesn't seem to be possible to drop the custom Python overrides for `Modulemd.ModuleStream.read_file()` and `Modulemd.ModuleStream.read_string()` because otherwise they will be returning a tuple again--which is what originally necessitated adding the overrides with the `ModulemdUtil.strip_gtype()` wrapper trickiness.

2021-01-04 19:27 UTC, sgallagher commented
> It doesn't seem to be possible to drop the custom Python overrides for `Modulemd.ModuleStream.read_file()` and `Modulemd.ModuleStream.read_string()` because otherwise they will be returning a tuple again--which is what originally necessitated adding the overrides with the `ModulemdUtil.strip_gtype()` wrapper trickiness.

I didn't say drop the overrides for `read_packager_file()`, I said we can just have the extended version of the function *be* read_packager_file() so far as the language bindings are concerned.

2021-01-05 13:53 UTC, sgallagher approved these changes
LGTM

The test failures appear to be a bug in the test runner that I need to track down.

2021-01-05 13:56 UTC, sgallagher commented
Actually... hang on. I'm somewhat concerned about the packit failures in the same place. We need to figure out why that's broken...

2021-01-05 14:46 UTC, mmathesius commented
> I think I found the issue. Have a look at [sgallagher@754ed25](https://github.com/sgallagher/libmodulemd/commit/754ed250fc10b8fd13a2da2937b582d8e20270b7)
> 
> Basically, we need to skip the test if the current installed environment doesn't have the appropriate override.

D'oh! That problem again. I should have remembered to include that.

Would you like me to add your commit to this PR? Actually, I think it would make it a little easier to comprehend if the test functions started out with the logic reversed, such as:
```
     if not (
         "_overrides_module" in dir(Modulemd)
         and hasattr(gi.overrides.Modulemd, "read_packager_file")
     ):
         return
```
What do you think?

> I still need to figure out why the "Other Architectures" aren't picking up the modified overrides, but that's a different problem.

I can try to look into that.

2021-01-05 15:01 UTC, sgallagher commented
> > I think I found the issue. Have a look at [sgallagher@754ed25](https://github.com/sgallagher/libmodulemd/commit/754ed250fc10b8fd13a2da2937b582d8e20270b7)
> > Basically, we need to skip the test if the current installed environment doesn't have the appropriate override.
> 
> D'oh! That problem again. I should have remembered to include that.
> 
> Would you like me to add your commit to this PR? Actually, I think it would make it a little easier to comprehend if the test functions started out with the logic reversed, such as:
> 
> ```
>      if not (
>          "_overrides_module" in dir(Modulemd)
>          and hasattr(gi.overrides.Modulemd, "read_packager_file")
>      ):
>          return
> ```
> 
> What do you think?

If you think it reads more cleanly that way, be my guest. I'd prefer if you integrated my changes (or this variant) directly into the patch that creates `common.py`. Otherwise it could potentially break a future `git bisect`.
> 
> > I still need to figure out why the "Other Architectures" aren't picking up the modified overrides, but that's a different problem.
> 
> I can try to look into that.

It's not urgent and we don't often change the overrides. We can file a bug on it and look into it whenever we get a free hour.

2021-01-05 15:45 UTC, merged